# Generated by Django 5.2 on 2025-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=38974980972, max_length=20),
            preserve_default=False,
        ),
    ]
